import type { Metadata } from "next";
import "./globals.scss";
import Layout from "@/Featured/Layout";
import { ThemeProvider } from "@/context";

export const metadata: Metadata = {
  title: "SearchArt",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <Layout>{children}</Layout>
        </ThemeProvider>
      </body>
    </html>
  );
}
