import type { Metadata } from "next";
import "./globals.scss";
import Layout from "@/Featured/Layout";

export const metadata: Metadata = {
  title: "SearchArt",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
